### ISSUE TITLE
Why .dockerignore ignores all files on /tmp and /tmp/*.log

### ISSUE THREAD

**Issue by neohunter** [cpuguy83/docker-rails-dev-demo#2]
On your `.dockerignore` you have this:

```
# Ignore the temporary files:
/tmp/*
/log/*.log
```

Which makes no sense for me, the first line is not ignoring already what the 2nd tries to do?

**Comment by cpuguy83** [comment]
No.
First line is ignoring `tmp/`
Secdond line is ignoring `log/`
